zelda_homepage:
    path:     /
    defaults: { _controller: ZeldaBundle:Zelda:index }

zelda_categorie:
    path:     /categ
    defaults: { _controller: ZeldaBundle:Zelda:afficherCateg }

zelda_item:
    path:     /item/{id}
    defaults: { _controller: ZeldaBundle:Zelda:afficherItem, id: 1 }
    requirements:
                id: \d+

zelda_monstre:
    path:     /monstre/{id}
    defaults: { _controller: ZeldaBundle:Zelda:afficherMonstre, id: 1 }
    requirements:
                id: \d+

zelda_categorieMonstre:
    path:     /monstreCateg
    defaults: { _controller: ZeldaBundle:Zelda:afficherMonstreCateg}

zelda_materiau:
    path:     /materiau/{id}
    defaults: { _controller: ZeldaBundle:Zelda:afficherMat, id: 1 }
    requirements:
                id: \d+

zelda_categorieMat:
    path:     /matCateg
    defaults: { _controller: ZeldaBundle:Zelda:afficherMatCateg}

zelda_categorieAnimaux:
    path:     /animauxCateg
    defaults: { _controller: ZeldaBundle:Zelda:afficherAnimalCateg}

zelda_animaux:
    path:     /animaux/{id}
    defaults: { _controller: ZeldaBundle:Zelda:afficherAnimal, id: 1}
    requirements:
                id: \d+