zelda_homepage:
    path:     /
    defaults: { _controller: ZeldaBundle:Zelda:index }

zelda_categorie:
    path:     /categ/{id}
    defaults: { _controller: ZeldaBundle:Zelda:afficherCateg, id: 1 }
    requirements:
                id: \d+

zelda_item:
    path:     /item/{id}
    defaults: { _controller: ZeldaBundle:Zelda:afficherItem, id: 1 }
    requirements:
                id: \d+
