<?php

namespace ZeldaBundle\Repository;

/**
 * AnimauxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnimauxRepository extends \Doctrine\ORM\EntityRepository
{
}
