<?php

namespace ZeldaBundle\Repository;

/**
 * AnimauxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnimauxRepository extends \Doctrine\ORM\EntityRepository
{
    public function lesAutresAnimaux($id)
    {
        $qb = $this->createQueryBuilder('p')
            ->select('p')
            ->where('p.id != :id')
            ->setMaxResults(6)
            ->orderBy('p.laCategorieAnimaux')
            ->setParameter("id", $id);
        return $qb->getQuery()->getResult();
    }
}
