<?php

namespace ZeldaBundle\Repository;

/**
 * ArmeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArmeRepository extends \Doctrine\ORM\EntityRepository
{

    public function lesAutresArmes($id)
    {
        $qb=$this->createQueryBuilder('p')
            ->select('p')
            ->where('p.id != :id')
            ->setMaxResults(6)
            ->orderBy('p.laCategorie')
            ->setParameter("id",$id);
        return $qb->getQuery()->getResult();
    }
}
