<?php

namespace ZeldaBundle\Repository;

/**
 * ArmeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArmeRepository extends \Doctrine\ORM\EntityRepository
{
}
