<?php

namespace ZeldaBundle\Repository;

/**
 * CategorieMateriauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieMateriauRepository extends \Doctrine\ORM\EntityRepository
{
}
