<?php

namespace ZeldaBundle\Repository;

/**
 * CategorieMonstreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieMonstreRepository extends \Doctrine\ORM\EntityRepository
{
}
