<?php

namespace ZeldaBundle\Repository;

/**
 * CategorieAnimauxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieAnimauxRepository extends \Doctrine\ORM\EntityRepository
{
}
