<?php

namespace ZeldaBundle\Repository;

/**
 * MateriauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MateriauRepository extends \Doctrine\ORM\EntityRepository
{
}
