<?php

namespace ZeldaBundle\Repository;

/**
 * MonstreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MonstreRepository extends \Doctrine\ORM\EntityRepository
{
}
