<?php

namespace ZeldaBundle\Repository;

/**
 * MonstreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MonstreRepository extends \Doctrine\ORM\EntityRepository
{
    public function lesAutresMonstres($id)
    {
        $qb = $this->createQueryBuilder('p')
            ->select('p')
            ->where('p.id != :id')
            ->setMaxResults(6)
            ->orderBy('p.laCategorieMonstre')
            ->setParameter("id", $id);
        return $qb->getQuery()->getResult();
    }
}
